# Generated by Django 5.2 on 2025-05-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.editora'),
            preserve_default=False,
        ),
    ]
