# Generated by Django 5.2.1 on 2025-06-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_autor_item_autor'),
        ('app', '0004_editora_item_editora'),
    ]

    operations = [
    ]
